services:
  keigen-bot:
    build: .
    env_file: .env
    environment:
      - REDIS_HOST=keigen-redis
    depends_on:
      - keigen-redis
    restart: unless-stopped

  keigen-redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
