from langchain.agents import create_agent
from langchain.chat_models import init_chat_model

from const import GOOGLE_API_KEY

model = init_chat_model(
    model="google_genai:gemma-4-31b-it",
    api_key=GOOGLE_API_KEY,
    max_tokens=8192,
)

agent = create_agent(
    model,
    system_prompt=(
        "You are Keigen, an AI assistant for searching Kleinanzeigen. Your job is "
        "to help users find the best items they are looking for by using the "
        "provided search tools. Be concise, friendly, and output the markdown table "
        "generated by the tools directly to the user."
    ),
    name="Keigen",
)
